### ISSUE TITLE
algorithm is required on digest authentication

### ISSUE THREAD

**Issue by QuadrantAndrew** [apple/ccs-calendarserver#484]
The RFC says this field this as optional, but the txdav/who/directory.py assumes it's there.

Changing:
`credentials.fields.["algorithm"],`

To (MD5 is the default in the RFC):
`credentials.fields.get("algorithm","md5"),`

Fixes this issue.

**Comment by dreness** [comment]
Thanks for the patch.

bb57615..b6120bb  master -> master
