### ISSUE TITLE
installation guide 

### ISSUE THREAD

**Issue by f1-outsourcing** [apple/ccs-calendarserver#490]
> WARNING: these instructions are for running a server from the source tree, which is useful for development. These are not the correct steps for running the server in deployment or as part of an OS install. 

So put them then. Or at least link to them. Afaik this is common practice in the github projects I am 'following'.

**Comment by dreness** [comment]
There is no unpublished document that is being withheld - it simply doesn't exist. I did just now update [Guide.rst](https://github.com/apple/ccs-calendarserver/blob/master/doc/Admin/Guide.rst#installation) with a small amount of info about ./bin/package.
