### ISSUE TITLE
FYI: notice statements db creation

### ISSUE THREAD

**Issue by f1-outsourcing** [apple/ccs-calendarserver#498]
```
NOTICE:  identifier "calendar_object_revisions_resource_id_resource_name_deleted_revision" will be truncated to "calendar_object_revisions_resource_id_resource_name_deleted_rev"

NOTICE:  identifier "addressbook_object_revisions_owner_home_resource_id_resource_name_deleted_revision" will be truncated to "addressbook_object_revisions_owner_home_resource_id_resource_na"
```

**Comment by dreness** [comment]
This is probably ignorable, and would only become a problem if the the truncated name collided with another truncated name, which isn't happening currently.

Oracle has more strict rules on name lengths, so we have some stuff that handles names longer than the threshold by replacing a portion of the name with some form of hash of the entire name (or something like that); we could use that for Postgres if we ever had to, but probably won't be needed.
