### ISSUE TITLE
webcal / web interface 

### ISSUE THREAD

**Issue by f1-outsourcing** [apple/ccs-calendarserver#499]
What is this webcal? A http interface? How do you enable this?

![webcal](https://user-images.githubusercontent.com/13450219/28627610-969b4a4c-7222-11e7-9af8-3a5838d32ba2.jpg)

**Comment by dreness** [comment]
The webcal is a feature bundled with the CalendarServer distribution in Apple's macOS Server suite. It can be used with calendars owned by individuals, and also with calendars that belong to wiki groups, in conjunction with the wiki service of macOS Server. Unfortunately this webcal is not part of the open source CalendarServer distribution.
