### ISSUE TITLE
Setup ccs independent of macOS server - push?

### ISSUE THREAD

**Issue by freswa** [apple/ccs-calendarserver#508]
Since Apple will [deprecate](https://support.apple.com/en-us/HT208312) the ccs in the macOS server product, I decided to setup a server on a clean macOS install (High Sierra).
Seems doable, but I am missing the push notification certificates. How do I get them without macOS server?

**Comment by dreness** [comment]
@freswa - Apple’s developer portal can vend APNS certs, and those should work with this server and third party clients that support APNS (sadly, I know of none...). Unfortunately Apple’s calendar and contacts apps only support APNS when used with push certs issued to a bundle ID that can only be used by Apple (and only by Server.app). That is a policy decision, and if you’d like to push Calendar / Contacts apps using a standard 3rd party push cert, I encourage you to request this at bugreporter.apple.com.

There is one other push implementation supported by the server (based on the Python AMP module), but as far as I know, the only client that supports this is our client simulator (a server test tool).

Wish I had a better answer :/

**Comment by helje5** [comment]
I filed this: http://www.openradar.me/radar?id=6161001854533632
