### ISSUE TITLE
Should incoming IMIP message update the organizers event with acceptance status?

### ISSUE THREAD

**Issue by mocodev** [apple/ccs-calendarserver#533]
Should incoming IMIP message update the organizers event with acceptance status? Delivery of IMIP events is working as expected. We're just curious of the expected "acceptance" functionality.

Our current scenario is sending a calendar invite to a user with a @gmail.com address. The user receives the invite email, accepts the invite and its added to their Google calendar. Our mailbox receives the email that the user accepted the invite but the calendar event within Mac Calendar does not update the users status. Remains a gray question mark.

**Comment by m0rgen** [comment]
Have you checked the calendar server logs for any clues?  This inbound.py module should log what it’s doing when processing the inbox:

https://github.com/apple/ccs-calendarserver/blob/master/txdav/caldav/datastore/scheduling/imip/inbound.py

**Comment by mocodev** [comment]
Looking at the logs led us down the path of SSL errors which were ultimately due to an incorrect port used in our IMAP settings. inbound.py couldn't connect to the mail server. Once the connection issue was resolved, acceptance status worked as expected.
